---
- name: build interfaces 
  hosts: 10.42.254.1
  tasks:
    - ios_config:
      lines:
      - description test-ansible port
      - switchport mode access
      - spanning-tree portfast 
      - no shut
      parents: interface GigabitEthernet2/0/31
      config:  "{{ config.stdout[0] }}"
      provider: "{{ cli}}"
    - ios_command:
      commands: show lldp neighbors GigabitEthernet0/1 detail
      waitfor:  "result{0} contains 'System Name: iosxr02.eng.ansible.com"
      provider:  "{{ cli }}"
