---
- name: build interfaces 
  hosts: 10.42.254.1
  connection: network_cli
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version

  - name: run show version and check to see if output contains IOS
    ios_command:
      commands: show version
      wait_for: result[0] contains IOS
