---
- name: configure access vlan
  
  hosts: all
  
  connection: network_cli
  
  tasks:

 - name: Ensure GigabitEthernet2/0/35 is configured for access vlan 1142
  ios_l2_interface:
    name: GigabitEthernet2/0/35
    mode: access
    access_vlan: 1142
