---
- name: ios version output
  
  hosts: all
  
  connection: network_cli

  - name: run multiple commands on remote nodes
    ios_command:
      commands:
        - show version
        - show interfaces
        
  - name: configure interface
 
    ios_interface:
    name: GigabitEthernet2/0/30
    description: Device_name

 
