---
- name: ios version output
  gather facts: false
  
  hosts: all
  
  connection: network_cli
  
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
      commands: show cdp neighbor
