---
- name: ios version output
  hosts: 10.42.254.1
  connection: network_cli
  
  tasks:
  - name: run show version on remote devices
    ansible_network_os: ios
    ios_command:
      commands: show version
