---
- name: ios version output
  
  hosts: 10.42.254.1
  hosts: 10.42.254.25
  hosts: 10.42.254.26
  
  connection: network_cli
  
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
