---
- name: ios version output
    
  hosts: all
  
  connection: network_cli
  
  tasks:
  - ios_facts:
      gather_subset: 
        - "!all"
      
  - name: run show version on remote devices
    ios_command:
      commands: show version
      commands: show cdp neighbor
